# Generated by Django 3.1 on 2020-09-08 09:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave2', '0002_auto_20200901_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallInteger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('value', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('github_link', models.URLField(validators=[django.core.validators.URLValidator(), django.core.validators.RegexValidator(regex='github.com/.+/.+')])),
                ('is_full', models.BooleanField(default=False)),
                ('project_name', models.CharField(blank=True, max_length=100)),
                ('project_description', models.TextField(blank=True)),
                ('technologies', models.ManyToManyField(blank=True, to='wave2.Technology')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
