# Generated by Django 3.1 on 2020-09-14 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave2', '0004_log'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Date',
            new_name='FieldValidationDate',
        ),
        migrations.AddField(
            model_name='user',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='github_link',
            field=models.URLField(validators=[django.core.validators.URLValidator(), django.core.validators.RegexValidator(regex='(github.com/.+/.+/?,? ?)+')]),
        ),
    ]
