# Generated by Django 3.1 on 2020-09-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave2', '0005_auto_20200914_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.JSONField(),
        ),
    ]
