# Generated by Django 3.1 on 2020-10-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wave2', '0007_auto_20201004_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='date_created',
        ),
    ]
