# Generated by Django 3.1 on 2020-10-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave2', '0008_remove_team_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ready',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
