# Generated by Django 3.1 on 2020-10-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave2', '0009_team_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
