# Generated by Django 3.1 on 2020-11-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave2', '0011_user_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='online',
            new_name='is_online',
        ),
        migrations.AddField(
            model_name='user',
            name='discord_id',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
