# Generated by Django 3.1 on 2020-11-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wave2', '0013_auto_20201121_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='telephone',
            new_name='phone',
        ),
    ]
