# Generated by Django 3.1 on 2020-11-21 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave2', '0014_auto_20201121_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(regex='^0\\d{9}$')]),
        ),
    ]
