# Generated by Django 3.1 on 2020-12-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave2', '0017_auto_20201128_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='github_link',
            field=models.TextField(blank=True),
        ),
    ]
