# Generated by Django 3.1 on 2020-12-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave2', '0018_auto_20201206_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.BigIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
