# Generated by Django 3.1 on 2020-12-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave2', '0019_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='form',
            field=models.CharField(choices=[('8А', '8 А'), ('8Б', '8 Б'), ('8В', '8 В'), ('8Г', '8 Г'), ('9А', '9 А'), ('9Б', '9 Б'), ('9В', '9 В'), ('9Г', '9 Г'), ('10А', '10 А'), ('10Б', '10 Б'), ('10В', '10 В'), ('10Г', '10 Г'), ('11А', '11 А'), ('11Б', '11 Б'), ('11В', '11 В'), ('11Г', '11 Г'), ('12А', '12 А'), ('12Б', '12 Б'), ('12В', '12 В'), ('12Г', '12 Г')], max_length=4),
        ),
    ]
