# Generated by Django 3.1 on 2021-01-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wave2', '0020_auto_20201217_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
